In [1]:
!pip install pandas numpy scikit-learn

In [2]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

In [6]:
df = pd.read_csv("/content/Reviews.csv", on_bad_lines='skip', engine='python')

print(df.head())
print(df.shape)

  Id   ProductId          UserId                      ProfileName  \
0  1  B001E4KFG0  A3SGXH7AUHU8GW                       delmartian   
1  2  B00813GRG4  A1D87F6ZCVE5NK                           dll pa   
2  3  B000LQOCH0   ABXLMWJIXXAIN  Natalia Corres "Natalia Corres"   
3  4  B000UA0QIQ  A395BORC6FGVXV                             Karl   
4  5  B006K2ZZ7K  A1UQRSCLF8GW1T    Michael D. Bigham "M. Wassir"   

  HelpfulnessNumerator HelpfulnessDenominator Score        Time  \
0                    1                      1     5  1303862400   
1                    0                      0     1  1346976000   
2                    1                      1     4  1219017600   
3                    3                      3     2  1307923200   
4                    0                      0     5  1350777600   

                 Summary                                               Text  
0  Good Quality Dog Food  I have bought several of the Vitality canned d...  
1      Not as Advertised  

In [7]:
light_reviews = df[df['Text'].str.contains('light', case=False, na=False)]

print("Number of reviews containing 'light':", len(light_reviews))

Number of reviews containing 'light': 75453


In [8]:
for review in light_reviews['Text'].head(20):
    print(review)
    print("-"*100)

This is a confection that has been around a few centuries.  It is a light, pillowy citrus gelatin with nuts - in this case Filberts. And it is cut into tiny squares and then liberally coated with powdered sugar.  And it is a tiny mouthful of heaven.  Not too chewy, and very flavorful.  I highly recommend this yummy treat.  If you are familiar with the story of C.S. Lewis' "The Lion, The Witch, and The Wardrobe" - this is the treat that seduces Edmund into selling out his Brother and Sisters to the Witch.
----------------------------------------------------------------------------------------------------
I got a wild hair for taffy and ordered this five pound bag. The taffy was all very enjoyable with many flavors: watermelon, root beer, melon, peppermint, grape, etc. My only complaint is there was a bit too much red/black licorice-flavored pieces (just not my particular favorites). Between me, my kids, and my husband, this lasted only two weeks! I would recommend this brand of taffy --

In [9]:
sentence1 = "This olive oil is wonderful and very light on the stomach."

sentence2 = "The packaging was broken and let too much light inside the box."

sentence3 = "I prefer this brand because it is a light and healthy snack."

In [10]:
sentences = [sentence1, sentence2, sentence3]

In [11]:
vectorizer = CountVectorizer()

dtm = vectorizer.fit_transform(sentences)

In [12]:
dense_matrix = dtm.toarray()

print(dense_matrix)

[[1 0 0 0 0 0 0 1 0 0 1 0 1 1 1 0 0 0 1 1 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 0 1 1 1 0 0 0 1 0 0 0 2 0 1 0 1 0]
 [1 1 0 1 0 1 0 1 1 0 1 0 0 0 0 0 1 1 0 0 1 0 0 0 0]]


In [13]:
print(vectorizer.get_feature_names_out())

['and' 'because' 'box' 'brand' 'broken' 'healthy' 'inside' 'is' 'it' 'let'
 'light' 'much' 'oil' 'olive' 'on' 'packaging' 'prefer' 'snack' 'stomach'
 'the' 'this' 'too' 'very' 'was' 'wonderful']


In [14]:
vec_1 = dense_matrix[0]
vec_2 = dense_matrix[1]
vec_3 = dense_matrix[2]

print("Vector 1:", vec_1)
print("Vector 2:", vec_2)
print("Vector 3:", vec_3)

Vector 1: [1 0 0 0 0 0 0 1 0 0 1 0 1 1 1 0 0 0 1 1 1 0 1 0 1]
Vector 2: [1 0 1 0 1 0 1 0 0 1 1 1 0 0 0 1 0 0 0 2 0 1 0 1 0]
Vector 3: [1 1 0 1 0 1 0 1 1 0 1 0 0 0 0 0 1 1 0 0 1 0 0 0 0]


In [15]:
similarity_1_2 = np.dot(vec_1, vec_2)

In [16]:
similarity_1_3 = np.dot(vec_1, vec_3)

In [17]:
print("Similarity between Sentence 1 and Sentence 2:")
print(similarity_1_2)

print()

print("Similarity between Sentence 1 and Sentence 3:")
print(similarity_1_3)

Similarity between Sentence 1 and Sentence 2:
4

Similarity between Sentence 1 and Sentence 3:
4
